# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

############################
## Theme
############################
theme = "stanford"
font = "stanford"

# Enable users to switch between day and night mode?
day_night = false

# Choose a font size.
font_size = "L" # Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)

############################
## Basic Info
############################

# Website type
site_type = "Person"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = ""

# Display a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

############################
## Site Features
############################

# Enable source code highlighting? true/false
highlight = true
highlight_languages = ["r", "python", "latex"]  # Add support for highlighting additional languages
highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
math = true

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page = {repo_url = "https://github.com/NKeleher/academic-niall", content_dir = "", repo_branch = "master", editable = {docs = false, page = false, post = false}}

############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Enter contact details (optional). To hide a field, clear it to "".
email = "nkeleher@stanford.edu"
phone = ""

# Office hours
# A list of your office hours. To remove, set to an empty list `[]`.
office_hours = ["Email or sign up on calendly for appointments"]

# Enter an optional link for booking appointments (e.g. calendly.com).
appointment_url = "https://calendly.com/nkeleher"

# Address
# For country_code, use the 2-letter ISO code (see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 )
address = {street = "655 Knight Way", city = "Stanford", region = "CA", postcode = "94305", country = "United States", country_code = "US"}

# Geographic coordinates
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
coordinates = {latitude = "3", longitude = ""}

# Directions for visitors to locate you.
directions = "Office is in the basement of Bass Center, B002"

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  {icon = "twitter", icon_pack = "fab", name = "nkeleher", link = "https://twitter.com/nkeleher"},
  {icon = "linkedin", icon_pack = "fab", name = "niall-keleher", link = "https://www.linkedin.com/in/niall-keleher/"},
  # {icon = "skype", icon_pack = "fab", name = "nkeleher", link = "skype:nkeleher"},
  # {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  # {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  # {icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@Telegram"},
  ]

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter = "nkeleher"

############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

############################
## Advanced
############################

# Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  # custom_css = ['']
  # custom_js = ['']

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "r", show_logo = true}

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Link authors to their profile page? (true/false)
link_authors = false

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = []

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  de = {order = ['street', 'postcode', 'city'], delimiters = [', ', ' ', '']}
  fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

############################
## Comments
############################
[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 0

  # Which page types are commentable?
  commentable = {page = false, post = true, docs = false, project = true, publication = false, talk = false}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

  # Configuration of Commento.
  [comments.commento]
    # If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.
    url = ""

############################
## Search
############################
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 0

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

############################
## Maps
############################
[map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  engine = 0
  api_key = ""
  zoom = 15

############################
## Marketing
############################
[marketing]
  google_analytics = ""
  google_tag_manager = ""
